// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SourceServerManager.Infrastructure.Data;

#nullable disable

namespace SourceServerManager.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20221104182332_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.10");

            modelBuilder.Entity("SourceServerManager.Infrastructure.Data.Server", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<string>("DirectoryName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT COLLATE NOCASE");

                    b.Property<string>("Game")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Hostname")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LastSrcdsRun")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LastSteamCmdRun")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginToken")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxPlayerCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Port")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StartupMap")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DirectoryName")
                        .IsUnique();

                    b.ToTable("Servers");
                });
#pragma warning restore 612, 618
        }
    }
}
